src/
src/main/
src/main/java/
src/main/java/com/
src/main/java/com/liveaction/
src/main/java/com/liveaction/google/
src/main/java/com/liveaction/google/hashcode2019/
src/main/java/com/liveaction/google/hashcode2019/output/
src/main/java/com/liveaction/google/hashcode2019/output/writer/
src/main/java/com/liveaction/google/hashcode2019/output/writer/OutputWriter.java
src/main/java/com/liveaction/google/hashcode2019/input/
src/main/java/com/liveaction/google/hashcode2019/input/Input.java
src/main/java/com/liveaction/google/hashcode2019/model/
src/main/java/com/liveaction/google/hashcode2019/model/IndexedPhoto.java
src/main/java/com/liveaction/google/hashcode2019/model/Slide.java
src/main/java/com/liveaction/google/hashcode2019/model/TagMapping.java
src/main/java/com/liveaction/google/hashcode2019/model/Solver.java
src/main/java/com/liveaction/google/hashcode2019/model/Photo.java
src/main/java/com/liveaction/google/hashcode2019/model/Position.java
src/main/java/com/liveaction/google/hashcode2019/Hashcode2019Application.java
src/main/resources/
src/test/
src/test/java/
src/test/java/com/
src/test/java/com/liveaction/
src/test/java/com/liveaction/google/
src/test/java/com/liveaction/google/hashcode2019/
src/test/java/com/liveaction/google/hashcode2019/input/
src/test/java/com/liveaction/google/hashcode2019/input/InputTest.java
src/test/java/com/liveaction/google/hashcode2019/Hashcode2019ApplicationTest.java
src/test/java/com/liveaction/google/hashcode2019/model/
src/test/java/com/liveaction/google/hashcode2019/model/SolverTest.java
src/test/resources/
src/test/resources/c_memorable_moments.txt
src/test/resources/input4.in
src/test/resources/input2.in
src/test/resources/input3.in
src/test/resources/d_pet_pictures.txt
src/test/resources/b_lovely_landscapes.txt
src/test/resources/input1.in
src/test/resources/a_example.txt
src/test/resources/e_shiny_selfies.txt
pom.xml
